### ISSUE TITLE
Système de succès

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#10]
Une élection terminée avec un score égal ou supérieur au score historique débloque une affiche de l'époque (éventuellement pixellisée). Avantage : valorisation du patrimoine. Attention aux questions de droits.

**Comment by AnteJR** [comment]
On trouve pas mal d'affiches sur le [site de la Confédération](https://nb-posters.primo.exlibrisgroup.com/discovery/search?search_scope=MyInstitution&vid=41SNL_53_INST:posters&lang=fr). Je pense les reprendre en pixel art (pas "juste" les pixeliser), afin de me les ré-approprier (j'ajouterai un lien dans le README comme crédits).

**Comment by ipante** [comment]
Je n'osais pas te le proposer.

https://img.bleacherreport.net/img/images/photos/003/283/536/96a054c518571eb2a87e1f6c9bd480c4_crop_north.jpg?1424294504&w=3072&h=2048

**Comment by AnteJR** [comment]
Ça m'ennuie, j'ai pas réussi à trouver des affiches "OUI" pour le rachat des chemins de fer fédéraux. Mais le reste j'ai tout ! Plus qu'à les dessiner.

**Comment by ipante** [comment]
J'ai vraiment hâte de voir le résultat !

**Comment by AnteJR** [comment]
UPDATE : 5 affiches sur 10 faites, pour le moment je ne les ai pas encore uploadées, je ferai tout d'un coup quand ce sera prêt

**Comment by AnteJR** [comment]
Le système de succès est 100% opérationnel, il faut juste que je m'assure qu'on puisse les obtenir tous (par ex la première votation pour le moment c'est impossible)

**Comment by ipante** [comment]
la classe, on y est presque : tu as une votation sur la santé il me semble

**Comment by ipante** [comment]
si tel n'est pas le cas, tu pourrais ajouter l'AVS qui arrive : je t'expliquerai

**Comment by AnteJR** [comment]
Ok, j'attends de voir ce que tu vas me proposer

**Comment by AnteJR** [comment]
En attendant je bosse encore sur : 

1. Le balancing des votations pour qu'on puisse obtenir un succès
2. Un bouton pour revenir en arrière à la sélection des missions pour pouvoir aller voir les succès SANS recharger le jeu

**Comment by ipante** [comment]
yes bien vu

**Comment by AnteJR** [comment]
Voila, j'ai appliqué les changements discutés plus haut, je te laisse faire une nouvelle issue pour ce que tu mentionnais.

**Comment by AnteJR** [comment]
Je fais ce rapide message pour dire que le jeu est à ce stade pratiquement fini : il manque simplement les posters d'achievement pour les nouveaux scénarios. Je te laisse me redire si tout semble fonctionner pour toi déjà, mécaniquement, en playtestant.

**Comment by ipante** [comment]
Tu as push la nouvelle version sur itch.io ? Ce serait bien, histoire de pouvoir le faire tester un peu plus largement.


Isaac Pante
_______________

Directeur scientifique UNIL
dhCenter UNIL-EPFL

Président
Dpt. Sciences du Langage et de l'Information
Faculté des lettres

Conseiller scientifique en Transition numérique
Rectorat UNIL

UNIL-Chamberonne
Anthropole, Bureau 3138
Tél. 0041-78-623-34-04
isaacpante.net<https://isaacpante.net/>
https://unil.zoom.us/my/isaacpante

Le 26 sept. 2022 à 23:30 +0200, Joël Rimaz ***@***.***>, a écrit :

Je fais ce rapide message pour dire que le jeu est à ce stade pratiquement fini : il manque simplement les posters d'achievement pour les nouveaux scénarios. Je te laisse me redire si tout semble fonctionner pour toi déjà, mécaniquement, en playtestant.

**Comment by AnteJR** [comment]
Pas encore, je le fais ce soir (mais il manque encore 5 assets graphiques)

**Comment by AnteJR** [comment]
C'est fait si jamais :)
