### ISSUE TITLE
Supprimer le texte introductif au second passage

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#11]
Quand je termine une partie, soit
- je suis renvoyé à la scène de sélection des missions (et vois que son statut a changé)
- je suis renvoyé à la scène d'accueil (et je ne devrais pas subir le texte introductif à nouveau)

L'option 1 me semble préférable.

**Comment by AnteJR** [comment]
J'ai fait un mix des deux : 

1. Quand je finis un niveau, je suis renvoyé à la scène "levelSelect", sur le niveau joué ;
2. Après avoir lu une première fois le texte introductif, il ne réapparaîtra plus en pressant "play now" quand la page est rechargée.
