### ISSUE TITLE
Faire ressentir la pression de l'approche de la fin de l'élection

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#12]
Par exemple en
- faisant évoluer la couleur des "days left" avec une échelle de couleur qui va de blanc à rouge vif.
- ajouter un feedback audio (chrono ? rumeur qui augmente ?) quand les derniers jours arrivent

**Comment by AnteJR** [comment]
Je pense implémenter les deux. Je verrai comment je gère ça !

**Comment by AnteJR** [comment]
L'idée est là, j'ai juste des problèmes avec le son quand on speedrun avec mes intervals qui ne se clear pas

**Comment by AnteJR** [comment]
Bon, j'ai trouvé un work-around un peu bête mais qui fonctionne pas trop mal : on entend le bruit de chrono dès le tour 5, et sauf si on spam-click les bruits ne se répètent pas. Contrairement aux tours 1-5 où il fallait parfois attendre 30sec avant de passer au tour suivant, les niveau 6+ peuvent être joué bcp plus vites sans ça que ça bug.

Pas parfais mais pour le moment je n'arrive pas à faire autrement.

**Comment by ipante** [comment]
ça me semble amplement suffisant : je crois qu'une librairie de soutien pouvait résoudre le problème ; si je la retrouve, je te l'envoie.

**Comment by AnteJR** [comment]
Pour être parfaitement honnête, si tu trouves je peux bien tester, mais suite à des bugs en playtest j'ai préféré supprimer le son du "tic-tac" pour le moment.
