### ISSUE TITLE
ambiguïté du % pour optics

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#13]
Pourquoi ne pas préférer des entiers, du type "Optics + 0.02" ? Mathématiquement cela fait bizarre de voir + 2% : je m'attendais à ce que cela soit 2% du pourcentage actuel. A voir si cela surprend d'autres personnes.

**Comment by AnteJR** [comment]
Ah oui bonne idée

**Comment by AnteJR** [comment]
DONE, je te laisse regarder le dernier commit sur GitHub Pages. J'ai aussi supprimé les infos superflues (+0%), et ai changé les icônes (le ":" et le "%" notamment) pour les rendre plus claires et conventionnelles
