### ISSUE TITLE
assister la lecture de certains choix

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#18]
certaines images sont très explicites (RSR), d'autres moins (gens autour de la table, boîte postale) ; il serait intéressant d'offrir une aide à la lecture quelque part. Voici trois solutions potentielles : 

- ajouter un texte aux images (juste quelques mots : "ENVOIS POSTAUX")
- ajouter une page au tutoriel avec des vignettes réduites pour chaque activité
- ajouter une aide aux images (genre infobulle) pour qui veut comprendre

Si tu ne changes rien, je pense qu'il faut ajouter une question au protocole de test pour comprendre si les images sont bien décodées à chaque fois

**Comment by AnteJR** [comment]
Testé options 1 et 3, non concluant. L'option 2 est la meilleure.
