### ISSUE TITLE
niveau plus cool

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#19]
Les premières minutes d'un jeu sont souvent moins punitives, pour transmettre les mécaniques et donner l'envie de poursuivre. Ici, on peut imaginer que quelqu'un accumule les échecs. Cela correspond évidemment à l'expérience d'une personne qui vote en Suisse (hélas) et peut faire partie du design, mais il faut se poser la question tout de même. Dans tes tests, est-ce que les gens gagnent du premier coup ?

Est-ce qu'une mission devrait être plus simple que les autres ?

**Comment by AnteJR** [comment]
Mh ça dépend ce qu'on entend par simple : qui permet d'avoir une victoire facilement, ou qui permet d'avoir une victoire PARFAITE directement ? Si c'est le premier cas, la mission la plus simple est celle sur le romanche comme langue nationale. Si c'est le second, alors c'est celle sur l'assurance maladie de 1912.

Dans tous les cas, ces 2 missions se situent assez tôt dans le jeu, et je ne trouve pas la mission du rachat des trains particulièrement difficile (littéralement, cliquer uniquement sur les options du haut (ou même du bas, ça marche aussi) permet de d'avoir une victoire standard (votes > 50%)).

Donc si tu arrives à me pointer qqch de spécifique je suis preneur, sinon on verra dans les playtests, mais en l'état j'ai pas du tout l'impression que ce soit qqch de nécessaire.

**Comment by AnteJR** [comment]
Et au pire je vois ça comme une partie de l'apprentissage.

De plus, cela voudrait dire qu'il faut trouver une votation AVANT 1898 qui soit plus facile à gagner que le rachat des chemins de fer, puisque les niveaux sont triés par ordre chronologique (ce que je ne suis pas prêt à changer pour des raisons de clarté dans les propos historiques du jeu)

**Comment by ipante** [comment]
Tu as raison. J'ai retesté, ça tient. Ça peut être vu comme un choix de design. Il faudra être attentif au moment des tests.
