### ISSUE TITLE
Choix théoriquement impossible

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#20]
Plus d'argent, mais deux options trop coûteuses. C'est arrivé le dernier jour. Est-ce que cette situation conduit automatiquement à un FAIL ou est-ce que ce cas ne devrait pas arriver ?
![s2](https://user-images.githubusercontent.com/1324037/193754025-d84a9635-1fde-4b6c-b472-f6453e3e9f77.png)
![s1](https://user-images.githubusercontent.com/1324037/193754036-95e007c6-0f45-4e4a-bb35-56fa46cd29e1.png)

**Comment by AnteJR** [comment]
Ce qui se passe dans ces cas : le jeu est terminé. Si tu as + que 50%, c'est gagné, sinon, c'est perdu. Option implémentée il y a de ça un moment. Je ne vois pas pourquoi tu ferais un game over si tu as + que 50% de votes. 

OK, ça peut faire bizarre d'avoir l'impression de ne plus pouvoir avancer et de voir un écran qui dit "VICTOIRE" droit après (surtout s'il reste un tour), mais ça me semble la meilleure option quand même.

**Comment by ipante** [comment]
Yep, ça se tient.
