### ISSUE TITLE
Mise en évidence de la sélection de mission

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#3]
Par exemple via une mise en évidence au survol et un effet sonore

**Comment by AnteJR** [comment]
Done

**Comment by ipante** [comment]
Pourquoi pas via un carrousel, genre "sélection de mission", du type :

< Centrales nucélaires 19XX >

Bouton gauche droite pour se déplacer et espace pour valider.

Autre possibilité : créer un écran de sélection de perso à la Mortal Kombat avec les dates comme personnage, puis validation.

**Comment by AnteJR** [comment]
Mmh il faut que je regarde

**Comment by AnteJR** [comment]
Done, je te laisse me redire si tu aimes bien. J'ai fait un carousel.

**Comment by ipante** [comment]
Excellent. Je t'ajoute une autre suggestion.

**Comment by AnteJR** [comment]
Je clos cette issue du coup
