### ISSUE TITLE
1000 CHF pour rien ?

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#5]
On comprend mal que ce choix est en fait une mécanique de renflouement. Il faudrait trouver une mise en évidence.

**Comment by ipante** [comment]
![image_choix_etrange](https://user-images.githubusercontent.com/1324037/186271736-0ea93ce4-3402-4884-90b2-0a599f98496c.png)

**Comment by AnteJR** [comment]
Est-ce que tu arrives à être plus précis ? Est-ce un problème de mise en page, de background...?

**Comment by ipante** [comment]
Il y a une différence notable entre cet élément et tous les autres, puisque c'est le seul qui permet de renflouer les caisses, or l'image ne transmet pas directement cette notion. Puisque l'animation est de qualité, il me semble qu'une mise en évidence serait idéale. Elle pourrait être doublement codée (teinte différente du texte peut-être?)

Je recommanderais de tester avec quelques autre personnes pour voir si cet élément a bien été compris.

**Comment by AnteJR** [comment]
Après discussion avec des ami-e-s, j'ai choisi de highlighter les stats en haut de couleur, vert/blanc/rouge, selon si tu gagnes/garde/perd des points sur tes stats.

Je clos l'issue pour le moment, je la rouvrirai si tu le juges nécessaire.

**Comment by ipante** [comment]
ouep, ça me semble préférable comme ça.
