### ISSUE TITLE
Retirer le bouton "back" sur l'écran explicatif

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#6]
Inutile à mon avis, voire parasitant.

**Comment by AnteJR** [comment]
Juste avant une mission donc ? Ou quand on presse pour la première fois sur "play now", droit après l'écran titre ?

**Comment by ipante** [comment]
Quand on presse pour la 1ère fois sur play now.

**Comment by AnteJR** [comment]
Done
