### ISSUE TITLE
Image de fond par mission

### ISSUE THREAD

**Issue by ipante** [AnteJR/Vote_Now#9]
Proposer, en pixel art, une image de contexte pour chaque votation. Exemple : sur le nucléaire, image de centrale en fond (opacité élevée).

**Comment by AnteJR** [comment]
À quel moment ? Lors du texte explicatif avant lancement ?

**Comment by ipante** [comment]
Je dirais même au moment de la sélection : le carrousel emporte l'image, qui se retrouverait ensuite pour chaque votation. Mais à toi de voir la pertinence.

**Comment by AnteJR** [comment]
Bon bah plus qu'à fait 10 pixel-arts :P

**Comment by ipante** [comment]
I know. Mais puisque t'es bon et que ça profite au projet...
Eeeh oui, c'est comme ça qu'on arrive en enfer :D

**Comment by AnteJR** [comment]
J'ai fait les 2 premières missions, pour le moment ça fait planter si on veut accéder à la mission 3 et +, mais comme ça ça donne une idée.

Je me dis que, si le contraste est trop faible, il est possible de soit : 
- foncer l'image avec un rectangle sombre transparent
- les passer dans un filtre sépia
- les passer dans un filtre noir/blanc

**Comment by ipante** [comment]
Ecoute, c'est pas mal du tout je trouve ! Bravo pour les images.
Pour le contraste, tu devrais tester avec des gens.

**Comment by AnteJR** [comment]
Done, je verrai pour le contraste selon le feedback des gens.
